version: '3.4'

networks:
  wkt-dev:
    driver: bridge

services:
  api:
    image: api
    depends_on:
      - "db"
    build: ./wkt-track-backend
    volumes:
      - ./wkt-track-backend:/app
    ports:
      - "8080:2000"
    env_file:
      - .env
    environment:
      DB_CONNECTION_STRING: "host=${PG_HOST};port=${PG_PORT};database=${PG_DATABASE};username=${PG_USERNAME};password=${PG_PASSWORD}"
    networks:
      - wkt-dev

  db:
    env_file:
      - .env
    image: postgres:latest
    ports:
      - "5434:5432"
    restart: always
    volumes:
      - db_volume:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: "${PG_USERNAME}"
      POSTGRES_PASSWORD: "${PG_PASSWORD}"
      POSTGRES_DB: "${PG_DATABASE}"
    networks:
      - wkt-dev

volumes:
  db_volume:
