version: '3.4'

networks:
  wkt-dev:
    driver: bridge

services:
  react_image:
    image: react
    tty: true
    ports: 
      - "3002:3000"
    volumes:
      - './wkt-track-frontend:/app'
      - '/app/node_modules'
    environment:
      - CHOKIDAR_USEPOLLING=true
    build:
      ./wkt-track-frontend
    networks:
      - wkt-dev
